In [53]:
import numpy as np
import scipy.linalg as sln
import matplotlib.pyplot as plt
import warnings
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

Points
<br># -> Doc(Main)
<br>## -> My Notes
<br>### -> Missing, Corrections to do

In [54]:
def mv(A, v, transp_flag):
    if transp_flag == 0:
        return A @ v
    else:
        return A.T @ v

In [55]:
def unv(j, n):
    e = np.zeros(n)
    e[j] = 1
    return e

In [56]:
def element(A, i=None, j=None):
    # Handling default arguments
    if i is None:
        i = slice(None)  # Selecting all rows
    if j is None:
        j = slice(None)  # Selecting all columns

    if isinstance(A, np.ndarray):  # Matrix
        if min(A.shape) > 1:  # Check if A is not a vector
            if isinstance(i, list) and isinstance(j, list):
                e = A[np.ix_(i, j)]
            else:
                e = A[i, j]
        else:
            e = A[i] if isinstance(i, list) else A[i]
    
    return e

In [57]:
def krylov_ata(A, v1=None, k=10, full=1, reortho=2):
    if v1 is None:
        v1 = np.random.randn(A.shape[1])

    k = min(k, min(A.shape))

    alpha = np.zeros(k)
    beta = np.zeros(k if full else k-1)

    len_v1 = len(v1)
    if reortho:
        V = np.zeros((len_v1, k + 1))
        V[:, 0] = v1 / np.linalg.norm(v1)
        #U = np.zeros((A.shape[0], k))
    else:
        v = v1 / np.linalg.norm(v1)

    for j in range(k):
        if reortho:
            r = A @ V[:, j]
            if j == 0 and reortho == 2:
                U = np.zeros((len(r), k))
        else:
            r = A @ v

        if j > 0:
            if reortho == 2:
                r -= beta[j-1] * U[:, j-1]
                r -= U[:, :j] @ (U[:, :j].T @ r)
            else:
                r -= beta[j-1] * u
        alpha[j] = np.linalg.norm(r)
        if alpha[j] == 0:
            break

        if reortho == 2:
            U[:, j] = r / alpha[j]
            r = A.T @ U[:, j]
        else:
            u = r / alpha[j]
            r = A.T @ u

        if reortho:
            r -= alpha[j] * V[:, j]
            r -= V[:, :j+1] @ (V[:, :j+1].T @ r)
        else:
            r -= alpha[j] * v

        if j < k - 1 or full:
            beta[j] = np.linalg.norm(r)
            if beta[j] == 0:
                break

            if reortho:
                V[:, j+1] = r / beta[j]
            else:
                v = r / beta[j]

    if not reortho:
        V = v
    if reortho < 2:
        U = u
    
    return V, U, alpha, beta

In [58]:
def krylov_ata_expand(A, V, U, c, k=10):
    m = V.shape[1]
    V = np.concatenate((V, np.zeros((V.shape[0], k))), axis=1)
    U = np.concatenate((U, np.zeros((U.shape[0], k))), axis=1)
    alpha = np.zeros(k)
    beta = np.zeros(k)
    

    for j in range(m, k + m):
        if j == m:
            r = A @ V[:, j - 1] - (U[:, :j - 1] @ c.T)
        else:
            r = A @ V[:, j - 1] - beta[j - m - 1] * U[:, j - 2]

        r -= - U[:, :j - 1] @ (U[:, :j - 1].T @ r)
        alpha[j - m] = np.linalg.norm(r)
        if alpha[j - m] == 0:
            break
        U[:, j - 1] = r / alpha[j - m]
        r = A.T @ U[:, j - 1] - alpha[j - m] * V[:, j - 1]
        r -= V[:, :j] @ (V[:, :j].T @ r)
        beta[j - m] = np.linalg.norm(r)
        if beta[j - m] == 0:
            break
        V[:, j] = r / beta[j - m]

    return V, U, alpha, beta

In [59]:
def krylov_schur_svd(A, v1 = None, nr = 1, tol = 1e-6, absrel = 'rel', mindim = 10, maxdim = 20, maxit = 1000, target = np.inf, info = 1):
    if v1 is None:
        v1 = np.random.rand(A.shape[1])
    if mindim < nr:
        mindim = nr
    if maxdim < 2 * mindim:
        maxdim = 2 * mindim
    if absrel == 'rel':
        tol *= np.linalg.norm(A, 1)

    B = np.zeros((maxdim, maxdim + 1))
    print(1)
    # Slow Here
    V, U, alpha, beta = krylov_ata(A, v1, mindim)
    print(2)
    # Bidiagonal Form for the first mindim rows and cols
    B[:mindim + 1, :mindim + 1] = np.diag(np.append(alpha, [0])) + np.diag(beta, 1)
    hist = np.zeros(maxit, dtype=np.float64)    
    np.set_printoptions(precision=12) 
    # Modified MATLAB code ordering
    print(3)
    # Slow Here
    v, u, a, b = krylov_ata_expand(A, V, U, B[:mindim, mindim], maxdim - mindim)
    print(4)
    for k in range(maxit):
        V, U, alpha, beta = v.copy(), u.copy(), a.copy(), b.copy()
        print(5)
        B[mindim: maxdim, mindim: maxdim] = np.diag(alpha) + np.diag(beta[:maxdim - mindim - 1], 1)        
        B[maxdim - 1, maxdim] = beta[maxdim - mindim - 1]
        X, sigma, Y = np.linalg.svd(B[:maxdim, :maxdim])
        # Restart of Lanczos algorithm
        V = np.concatenate((element(V[:, :maxdim] @ Y, list(range(V.shape[0])), list(range(mindim))), V[:, maxdim:maxdim + 1]), axis=1)
        U = element(U[:, :maxdim] @ X, list(range(U.shape[0])), list(range(mindim)))    
        c = B[:, maxdim]
        e = (c @ X)[:mindim]
        B[:mindim, :mindim + 1] = np.concatenate((np.diag(sigma[:mindim]), e.reshape(-1, 1)), axis=1)
        err = np.linalg.norm(e[:nr])
        hist[k] = err
        
        if info:
            print(str(k) + ": " + str(hist[k]))
        if err < tol:
            sigma = sigma[:nr]
            V = V[:, :nr]
            U = U[:, :nr]
            mvs = np.arange(1, k + 1) * (maxdim - mindim) + mindim
            print(f"Found after {k + 1} iteration(s) with residual = {err}")
            return sigma, V, U, hist[:k+1], mvs
    
    mvs = 2 * (np.arange(1, k + 1) * (maxdim - mindim) + mindim)
    if info:
        print(f"Quit after max {k + 1} iterations with residual = {err}")
    sigma = sigma[:mindim]
    V = V[:, :mindim]
    return sigma, V, U, hist, mvs

Tests

In [60]:
A = np.random.rand(200,100)
A

array([[ 0.7774,  0.2966,  0.2683, ...,  0.9407,  0.4727,  0.3139],
       [ 0.7048,  0.3883,  0.5921, ...,  0.0556,  0.7865,  0.2805],
       [ 0.0492,  0.1804,  0.7754, ...,  0.7167,  0.0782,  0.2551],
       ...,
       [ 0.6480,  0.2975,  0.5128, ...,  0.4523,  0.0063,  0.8240],
       [ 0.0193,  0.2992,  0.0612, ...,  0.0792,  0.6428,  0.4421],
       [ 0.6451,  0.4405,  0.2483, ...,  0.9495,  0.7469,  0.6620]])

In [61]:
sigma, V, U, hist, mvs = krylov_schur_svd(A, info=2,tol=1e-200,maxit= 7,nr= 3)

1
2
3
4
5
0: 0.032879947673891075
5
1: 0.004548104020152201
5
2: 0.0003375504022586548
5
3: 2.2701340659420908e-05
5
4: 1.353327271910905e-06
5
5: 7.748206487214467e-08
5
6: 4.425950559940474e-09
Quit after max 7 iterations with residual = 4.425950559940474e-09


In [62]:
hist

array([3.287994767389e-02, 4.548104020152e-03, 3.375504022587e-04,
       2.270134065942e-05, 1.353327271911e-06, 7.748206487214e-08,
       4.425950559940e-09])

In [63]:
mvs

array([ 40,  60,  80, 100, 120, 140])