In [1]:
import numpy as np
from functions_from_matlab import krylov_ata

In [2]:
A = np.array([[1,2,3,4],[3,5,2,8],[5,3,45,6],[2,1,6,3]])
print(A)
v1 = np.array([1, 4, 3, 7])
V,U,alpha,beta = krylov_ata(A,v1, k = 4)

[[ 1  2  3  4]
 [ 3  5  2  8]
 [ 5  3 45  6]
 [ 2  1  6  3]]
[ 5.3116  9.8150  22.4012  5.1962]
[ 1.2869 -1.2416  39.8975  4.6565]
[-0.2627 -2.0142  1.1686 -0.9649]
[-0.2483  0.2610  0.0886 -0.6213]


In [3]:
U

array([[ 0.2078, -0.3316,  0.6418, -0.6595],
       [ 0.3840, -0.8085, -0.0940,  0.4360],
       [ 0.8764,  0.4655,  0.0649,  0.1052],
       [ 0.2033, -0.1407, -0.7583, -0.6032]])

In [4]:
beta

array([ 35.7029,  2.3952,  0.2930,  0.0000])